import type { Family } from "./sprites";

export interface SkinDef {
  id: string;
  name: string;
  price: number;
  blurb: string;
  body: string;
  belly: string;
  outline: string;
  accent: string;
  trail: string;
  trailKind: TrailKind;
  accessory: Accessory;
  freckles?: boolean;
  turnFx: TurnFx;
  turnSnd: TurnSnd;
  turnColor: string;
  /** Milestone reward: unlocked forever the first time you climb this many stairs in one run. */
  unlockAt?: number;
  /** Silhouette family. Defaults to "blob" if omitted. */
  family?: Family;
}

export type Accessory =
  | "none"
  | "cap"
  | "ribbon"
  | "headband"
  | "crown"
  | "antenna"
  | "horns"
  | "halo"
  | "sprout"
  | "ears"
  | "headphones"
  | "flower"
  | "goggles"
  | "bandana"
  | "beret"
  | "tophat"
  | "beanie"
  | "party"
  | "scarf"
  | "monocle"
  | "bat";

export type TrailKind = "puff" | "spark" | "flame" | "star";

/** What a turn looks like for this character. */
export type TurnFx =
  | "ring"      // expanding shockwave square
  | "poof"      // soft smoke puffs
  | "sparkle"   // twinkling stars
  | "flame"     // fire burst
  | "zap"       // electric crackle
  | "confetti"  // multicolour squares
  | "bubble"    // rising bubbles
  | "stardust"  // big cosmic stars
  | "leaf"      // swirling leaves
  | "heart"     // floating hearts
  | "snow"      // gentle snowfall
  | "note";     // musical notes

/** What a turn sounds like for this character. */
export type TurnSnd =
  | "pop" | "woosh" | "chirp" | "zap" | "bling" | "whistle" | "buzz" | "chime"
  | "boing" | "twinkle" | "thud" | "splash";

export const SKINS: SkinDef[] = [
  /* ================================================================
     TIER 0 — STARTER
     ================================================================ */
  {
    id: "bloo",
    name: "Bloo",
    price: 0,
    blurb: "The default little climber. Small blob, big dreams.",
    body: "#45d6e6",
    belly: "#c9f7ff",
    outline: "#0e7f9e",
    accent: "#0e7f9e",
    trail: "#9ef2ff",
    trailKind: "puff",
    accessory: "none",
    turnFx: "ring",
    turnSnd: "pop",
    turnColor: "#9ef2ff",
    family: "blob",
  },

  /* ================================================================
     TIER 1 — EARLY GAME (50–250)
     ================================================================ */
  {
    id: "scout",
    name: "Scout",
    price: 50,
    blurb: "Trail-blazing orange rookie with a lucky cap.",
    body: "#ff8c42",
    belly: "#ffe3c2",
    outline: "#b04c12",
    accent: "#e3502f",
    trail: "#ffd9a0",
    trailKind: "puff",
    accessory: "cap",
    turnFx: "confetti",
    turnSnd: "whistle",
    turnColor: "#ff8c42",
    family: "blob",
  },
  {
    id: "momo",
    name: "Momo",
    price: 120,
    blurb: "Bubblegum speedster. The bow is aerodynamic. Probably.",
    body: "#ff7bac",
    belly: "#ffd3e4",
    outline: "#b03a68",
    accent: "#e8467f",
    trail: "#ffb1cf",
    trailKind: "spark",
    accessory: "ribbon",
    turnFx: "sparkle",
    turnSnd: "chirp",
    turnColor: "#ffb1cf",
    family: "cat",
  },
  {
    id: "kage",
    name: "Kage",
    price: 250,
    blurb: "Silent feet, crimson headband, zero wasted hops.",
    body: "#4a5878",
    belly: "#aab6d6",
    outline: "#232c44",
    accent: "#ff4757",
    trail: "#8fa0ff",
    trailKind: "spark",
    accessory: "headband",
    turnFx: "zap",
    turnSnd: "zap",
    turnColor: "#8fa0ff",
    family: "knight",
  },

  /* ================================================================
     TIER 2 — MID GAME (300–700)
     ================================================================ */
  {
    id: "pip",
    name: "Pip",
    price: 300,
    blurb: "A cheerful sprout who grows a little with every floor.",
    body: "#6fce5a",
    belly: "#d6f7c3",
    outline: "#2e7a2a",
    accent: "#3a8a30",
    trail: "#c9f7a0",
    trailKind: "puff",
    accessory: "sprout",
    turnFx: "bubble",
    turnSnd: "chirp",
    turnColor: "#aef29e",
    family: "blob",
  },
  {
    id: "gloop",
    name: "Gloop",
    price: 380,
    blurb: "Slightly radioactive, mostly friendly. Sloshes its way up.",
    body: "#a2ff00",
    belly: "#e1ffb3",
    outline: "#598c00",
    accent: "#ff007f",
    trail: "#c4ff4d",
    trailKind: "puff",
    accessory: "sprout",
    turnFx: "bubble",
    turnSnd: "buzz",
    turnColor: "#c4ff4d",
    family: "blob",
  },
  {
    id: "rey",
    name: "Rey",
    price: 450,
    blurb: "Claims every staircase is a throne room staircase.",
    body: "#8f6fe8",
    belly: "#e0d4ff",
    outline: "#4b3290",
    accent: "#ffd23f",
    trail: "#d3b8ff",
    trailKind: "spark",
    accessory: "crown",
    turnFx: "sparkle",
    turnSnd: "bling",
    turnColor: "#ffd23f",
    family: "fancy",
  },
  {
    id: "bones",
    name: "Bones",
    price: 500,
    blurb: "Just a spooky little construct doing its best.",
    body: "#e0e0ce",
    belly: "#b5b5a4",
    outline: "#42423a",
    accent: "#e63946",
    trail: "#f1faee",
    trailKind: "puff",
    accessory: "horns",
    turnFx: "poof",
    turnSnd: "pop",
    turnColor: "#a8dadc",
    family: "ghost",
  },
  {
    id: "sunny",
    name: "Sunny",
    price: 650,
    blurb: "Woke up before the sun. Has never been late since.",
    body: "#ffd23f",
    belly: "#fff0bd",
    outline: "#b07a12",
    accent: "#ff8c42",
    trail: "#ffe9a3",
    trailKind: "spark",
    accessory: "ears",
    turnFx: "sparkle",
    turnSnd: "pop",
    turnColor: "#ffe9a3",
    family: "cat",
  },
  {
    id: "unit7",
    name: "Unit-7",
    price: 700,
    blurb: "Calibrated for verticality. Antenna pings the summit.",
    body: "#8fa8bd",
    belly: "#dceaf5",
    outline: "#3d5163",
    accent: "#ffd23f",
    trail: "#aefcff",
    trailKind: "spark",
    accessory: "antenna",
    turnFx: "zap",
    turnSnd: "buzz",
    turnColor: "#aefcff",
    family: "robot",
  },

  /* ================================================================
     TIER 3 — UPPER MID (750–1200)
     ================================================================ */
  {
    id: "matcha",
    name: "Matcha",
    price: 800,
    blurb: "Calm, collected, and highly caffeinated.",
    body: "#adc178",
    belly: "#dde5b6",
    outline: "#6c584c",
    accent: "#a98467",
    trail: "#dde5b6",
    trailKind: "puff",
    accessory: "flower",
    turnFx: "bubble",
    turnSnd: "whistle",
    turnColor: "#adc178",
    family: "blob",
  },
  {
    id: "vapor",
    name: "Vapor",
    price: 850,
    blurb: "A retro-synth wave runner listening to lo-fi beats.",
    body: "#7000ff",
    belly: "#ff00aa",
    outline: "#310070",
    accent: "#00ffff",
    trail: "#ff00aa",
    trailKind: "spark",
    accessory: "headphones",
    turnFx: "confetti",
    turnSnd: "zap",
    turnColor: "#00ffff",
    family: "robot",
  },
  {
    id: "dash",
    name: "Dash",
    price: 1000,
    blurb: "Climbs at 180 BPM. The headphones are not optional.",
    body: "#ff6a5e",
    belly: "#ffd0c9",
    outline: "#a02c24",
    accent: "#2f3340",
    trail: "#ffb3a8",
    trailKind: "spark",
    accessory: "headphones",
    turnFx: "zap",
    turnSnd: "buzz",
    turnColor: "#ff9d94",
    family: "robot",
  },
  {
    id: "ember",
    name: "Ember",
    price: 1000,
    blurb: "Leaves a scorch mark on every riser. Very sorry about it.",
    body: "#ff5c3d",
    belly: "#ffc9a3",
    outline: "#8a2413",
    accent: "#5c130a",
    trail: "#ffb347",
    trailKind: "flame",
    accessory: "horns",
    turnFx: "flame",
    turnSnd: "woosh",
    turnColor: "#ffb347",
    family: "knight",
  },
  {
    id: "frost",
    name: "Frost",
    price: 1200,
    blurb: "An absolute chill dude. Condensation follows him.",
    body: "#a8dedc",
    belly: "#f1faee",
    outline: "#457b9d",
    accent: "#1d3557",
    trail: "#f1faee",
    trailKind: "spark",
    accessory: "ears",
    turnFx: "ring",
    turnSnd: "chime",
    turnColor: "#a8dedc",
    family: "ghost",
  },

  /* ================================================================
     TIER 4 — HIGH END (1300–2200)
     ================================================================ */
  {
    id: "luna",
    name: "Luna",
    price: 1300,
    blurb: "Keeps a pressed flower from every sunrise she outruns.",
    body: "#b79df0",
    belly: "#e6dcff",
    outline: "#5e4496",
    accent: "#ff7bac",
    trail: "#d9c9ff",
    trailKind: "star",
    accessory: "flower",
    freckles: true,
    turnFx: "stardust",
    turnSnd: "chime",
    turnColor: "#e6dcff",
    family: "fancy",
  },
  {
    id: "honey",
    name: "Honey",
    price: 1400,
    blurb: "Sticky feet make vertical surfaces significantly easier.",
    body: "#ffb703",
    belly: "#ffdd00",
    outline: "#fb8500",
    accent: "#219ebc",
    trail: "#ffdd00",
    trailKind: "puff",
    accessory: "antenna",
    turnFx: "bubble",
    turnSnd: "buzz",
    turnColor: "#ffb703",
    family: "cat",
  },
  {
    id: "nova",
    name: "Nova",
    price: 1500,
    blurb: "Fallen from the top of the sky. Climbing back up.",
    body: "#3a2a6e",
    belly: "#7a5fc0",
    outline: "#191138",
    accent: "#ffe9a3",
    trail: "#fff3b0",
    trailKind: "star",
    accessory: "halo",
    freckles: true,
    turnFx: "stardust",
    turnSnd: "chime",
    turnColor: "#fff3b0",
    family: "fancy",
  },
  {
    id: "prism",
    name: "Prism",
    price: 2200,
    blurb: "Forged from refraction. Splits incoming light into hard angles.",
    body: "#ffffff",
    belly: "#e3f2fd",
    outline: "#78909c",
    accent: "#ff4081",
    trail: "#b3e5fc",
    trailKind: "star",
    accessory: "goggles",
    freckles: true,
    turnFx: "confetti",
    turnSnd: "bling",
    turnColor: "#ffeb3b",
    family: "fancy",
  },

  /* ================================================================
     TIER 5 — PREMIUM ENDGAME (3500–5000)
     ================================================================ */
  {
    id: "void",
    name: "Void",
    price: 3500,
    blurb: "A localized singularity. The gravity pulls steps toward it.",
    body: "#0b0914",
    belly: "#211c38",
    outline: "#000000",
    accent: "#9d4edd",
    trail: "#3c096c",
    trailKind: "star",
    accessory: "horns",
    turnFx: "stardust",
    turnSnd: "woosh",
    turnColor: "#7b2cbf",
    family: "ghost",
  },
  {
    id: "nebula",
    name: "Nebula",
    price: 5000,
    blurb: "The absolute zenith climber. Wears the cosmos like a coat.",
    body: "#ff007f",
    belly: "#7f00ff",
    outline: "#20003b",
    accent: "#00f5d4",
    trail: "#00f5d4",
    trailKind: "star",
    accessory: "crown",
    freckles: true,
    turnFx: "stardust",
    turnSnd: "chime",
    turnColor: "#ffe5ec",
    family: "fancy",
  },

  /* ================================================================
     MILESTONE CLIMBERS — earned by climbing
     ================================================================ */
  {
    id: "zip",
    name: "Zip",
    price: 0,
    blurb: "The 100-stair rookie. Goggles on, never late.",
    body: "#b6f04a",
    belly: "#eaffc0",
    outline: "#5f8f1e",
    accent: "#3c5a14",
    trail: "#eaffb0",
    trailKind: "spark",
    accessory: "goggles",
    turnFx: "zap",
    turnSnd: "buzz",
    turnColor: "#d8ff7a",
    unlockAt: 100,
    family: "robot",
  },
  {
    id: "bubba",
    name: "Bubba",
    price: 0,
    blurb: "Soft paws, steady pace. Reached stair 200.",
    body: "#c08a56",
    belly: "#f2dcb8",
    outline: "#6e4a24",
    accent: "#8f6234",
    trail: "#f2dcb8",
    trailKind: "puff",
    accessory: "ears",
    turnFx: "ring",
    turnSnd: "pop",
    turnColor: "#f2dcb8",
    unlockAt: 200,
    family: "cat",
  },
  {
    id: "sarge",
    name: "Sarge",
    price: 0,
    blurb: "Drills stairs before breakfast. Stair 300 checked in.",
    body: "#8a9c52",
    belly: "#d8e8a0",
    outline: "#43522a",
    accent: "#3c4a26",
    trail: "#d8e8a0",
    trailKind: "spark",
    accessory: "cap",
    turnFx: "confetti",
    turnSnd: "whistle",
    turnColor: "#c8e06a",
    unlockAt: 300,
    family: "knight",
  },
  {
    id: "wisp",
    name: "Wisp",
    price: 0,
    blurb: "Barely touches the steps. Met at stair 400.",
    body: "#cfe4ff",
    belly: "#ffffff",
    outline: "#7a9cc8",
    accent: "#8fb8e8",
    trail: "#e8f4ff",
    trailKind: "star",
    accessory: "halo",
    freckles: true,
    turnFx: "sparkle",
    turnSnd: "chime",
    turnColor: "#ffffff",
    unlockAt: 400,
    family: "ghost",
  },
  {
    id: "rex",
    name: "Rex",
    price: 0,
    blurb: "Tiny arms, enormous ambition. Tamed at stair 500.",
    body: "#58c24a",
    belly: "#c9f0a8",
    outline: "#22702a",
    accent: "#2e7d32",
    trail: "#ff8c42",
    trailKind: "flame",
    accessory: "horns",
    turnFx: "flame",
    turnSnd: "woosh",
    turnColor: "#ffb347",
    unlockAt: 500,
    family: "long",
  },
  {
    id: "aero",
    name: "Aero",
    price: 0,
    blurb: "Breaking sound barriers. Met at stair 750.",
    body: "#00f5d4",
    belly: "#ffffff",
    outline: "#00bbf9",
    accent: "#f15bb5",
    trail: "#9b5de5",
    trailKind: "spark",
    accessory: "goggles",
    turnFx: "zap",
    turnSnd: "zap",
    turnColor: "#00f5d4",
    unlockAt: 750,
    family: "bird",
  },
  {
    id: "titan",
    name: "Titan",
    price: 0,
    blurb: "Heavy metal mountaineer. Unlocked at stair 1000.",
    body: "#4a4e69",
    belly: "#9a8c98",
    outline: "#22223b",
    accent: "#f2e9e1",
    trail: "#c9ada7",
    trailKind: "flame",
    accessory: "horns",
    turnFx: "flame",
    turnSnd: "woosh",
    turnColor: "#9a8c98",
    unlockAt: 1000,
    family: "knight",
  },
  {
    id: "deity",
    name: "Deity",
    price: 0,
    blurb: "Ascended past the skyline. Holy presence at stair 2000.",
    body: "#fffdf0",
    belly: "#fff9c4",
    outline: "#f57f17",
    accent: "#fff59d",
    trail: "#fffde7",
    trailKind: "star",
    accessory: "halo",
    freckles: true,
    turnFx: "stardust",
    turnSnd: "chime",
    turnColor: "#fff59d",
    unlockAt: 2000,
    family: "fancy",
  },

  /* ================================================================
     NEW ADDITIONS
     ================================================================ */
  {
    id: "pixel",
    name: "Pixel",
    price: 150,
    blurb: "8-bit heart, 4K determination. Glitches upward.",
    body: "#5cff5c",
    belly: "#c8ffc8",
    outline: "#1a7a1a",
    accent: "#ff00ff",
    trail: "#a0ffa0",
    trailKind: "spark",
    accessory: "antenna",
    turnFx: "zap",
    turnSnd: "buzz",
    turnColor: "#5cff5c",
    family: "robot",
  },
  {
    id: "moss",
    name: "Moss",
    price: 200,
    blurb: "Grows on you. Literally. Slow but unstoppable.",
    body: "#6b8e4e",
    belly: "#c4d9a0",
    outline: "#3a4f28",
    accent: "#8fbc5a",
    trail: "#d4e8a8",
    trailKind: "puff",
    accessory: "sprout",
    turnFx: "leaf",
    turnSnd: "chirp",
    turnColor: "#a8c87a",
    family: "blob",
  },
  {
    id: "coral",
    name: "Coral",
    price: 350,
    blurb: "Reef-bred and current-powered. The ocean's stair champion.",
    body: "#ff7f50",
    belly: "#ffd4c4",
    outline: "#b03a20",
    accent: "#ffb347",
    trail: "#ffc4a8",
    trailKind: "puff",
    accessory: "flower",
    turnFx: "bubble",
    turnSnd: "splash",
    turnColor: "#ffb347",
    family: "blob",
  },
  {
    id: "sprocket",
    name: "Sprocket",
    price: 550,
    blurb: "Steampunk tinkerer. Clanks up one cog at a time.",
    body: "#b8860b",
    belly: "#f0d9a0",
    outline: "#6b4e0a",
    accent: "#cd7f32",
    trail: "#e8c87a",
    trailKind: "flame",
    accessory: "goggles",
    turnFx: "poof",
    turnSnd: "thud",
    turnColor: "#e8c87a",
    family: "robot",
  },
  {
    id: "berry",
    name: "Berry",
    price: 600,
    blurb: "Sweet on the outside, seeds of steel within.",
    body: "#c71585",
    belly: "#ffb6e6",
    outline: "#7a0a52",
    accent: "#4b0082",
    trail: "#ff8fd4",
    trailKind: "spark",
    accessory: "ribbon",
    turnFx: "heart",
    turnSnd: "twinkle",
    turnColor: "#ff8fd4",
    family: "cat",
  },
  {
    id: "cloud",
    name: "Cloud",
    price: 750,
    blurb: "Floats more than climbs. Doesn't see the difference.",
    body: "#e8f4ff",
    belly: "#ffffff",
    outline: "#a0c4e8",
    accent: "#7ab8f5",
    trail: "#ffffff",
    trailKind: "puff",
    accessory: "halo",
    turnFx: "poof",
    turnSnd: "woosh",
    turnColor: "#d0e8ff",
    family: "ghost",
  },
  {
    id: "knight",
    name: "Knight",
    price: 900,
    blurb: "Sworn to protect the staircase. Has never lost a step.",
    body: "#708090",
    belly: "#c0c8d0",
    outline: "#2f4f4f",
    accent: "#ffd700",
    trail: "#a8b8c8",
    trailKind: "spark",
    accessory: "headband",
    turnFx: "ring",
    turnSnd: "chime",
    turnColor: "#ffd700",
    family: "knight",
  },
  {
    id: "jester",
    name: "Jester",
    price: 950,
    blurb: "Why so serious? Every stair is a punchline.",
    body: "#9b30ff",
    belly: "#e0c0ff",
    outline: "#4b0082",
    accent: "#ff4500",
    trail: "#d0a0ff",
    trailKind: "spark",
    accessory: "party",
    turnFx: "confetti",
    turnSnd: "boing",
    turnColor: "#ff4500",
    family: "fancy",
  },
  {
    id: "aurora",
    name: "Aurora",
    price: 1800,
    blurb: "Northern lights given form. Dances up the stairs.",
    body: "#00ff88",
    belly: "#a0ffd0",
    outline: "#007744",
    accent: "#ff00ff",
    trail: "#00ffcc",
    trailKind: "star",
    accessory: "crown",
    freckles: true,
    turnFx: "stardust",
    turnSnd: "twinkle",
    turnColor: "#00ffcc",
    family: "fancy",
  },
  {
    id: "pharaoh",
    name: "Pharaoh",
    price: 2000,
    blurb: "Ancient ruler of vertical monuments. The stairs obey.",
    body: "#d4af37",
    belly: "#f5e6a8",
    outline: "#8b6914",
    accent: "#1e90ff",
    trail: "#f5e6a8",
    trailKind: "spark",
    accessory: "crown",
    turnFx: "sparkle",
    turnSnd: "bling",
    turnColor: "#f5e6a8",
    family: "knight",
  },
  {
    id: "cyber",
    name: "Cyber",
    price: 2500,
    blurb: "Fully augmented. The stairs are just data to process.",
    body: "#1a1a2e",
    belly: "#16213e",
    outline: "#0f0f1a",
    accent: "#00ffcc",
    trail: "#00ffcc",
    trailKind: "spark",
    accessory: "headphones",
    turnFx: "zap",
    turnSnd: "zap",
    turnColor: "#00ffcc",
    family: "robot",
  },
  {
    id: "sakura",
    name: "Sakura",
    price: 2800,
    blurb: "Petals fall behind her. Each step is a haiku.",
    body: "#ffb7c5",
    belly: "#ffe0e8",
    outline: "#c76b7f",
    accent: "#8b4513",
    trail: "#ffd0d8",
    trailKind: "puff",
    accessory: "flower",
    freckles: true,
    turnFx: "leaf",
    turnSnd: "chime",
    turnColor: "#ffd0d8",
    family: "cat",
  },
  {
    id: "obsidian",
    name: "Obsidian",
    price: 3000,
    blurb: "Volcanic glass. Sharp edges, smooth climbs.",
    body: "#1c1c1c",
    belly: "#3a3a3a",
    outline: "#000000",
    accent: "#ff4500",
    trail: "#ff4500",
    trailKind: "flame",
    accessory: "horns",
    turnFx: "flame",
    turnSnd: "woosh",
    turnColor: "#ff4500",
    family: "knight",
  },
  {
    id: "eternal",
    name: "Eternal",
    price: 6000,
    blurb: "Has always been climbing. Will always be climbing.",
    body: "#ffffff",
    belly: "#f0f0ff",
    outline: "#d0d0ff",
    accent: "#ffd700",
    trail: "#ffffff",
    trailKind: "star",
    accessory: "halo",
    freckles: true,
    turnFx: "stardust",
    turnSnd: "chime",
    turnColor: "#ffd700",
    family: "fancy",
  },
  {
    id: "omega",
    name: "Omega",
    price: 7500,
    blurb: "The final form. The last stair. The beginning.",
    body: "#0a0a0a",
    belly: "#1a1a2e",
    outline: "#000000",
    accent: "#ff00ff",
    trail: "#ff00ff",
    trailKind: "star",
    accessory: "crown",
    freckles: true,
    turnFx: "stardust",
    turnSnd: "chime",
    turnColor: "#ff00ff",
    family: "fancy",
  },
  {
    id: "summit",
    name: "Summit",
    price: 0,
    blurb: "Reached the peak once. Never came back down. Stair 1500.",
    body: "#87ceeb",
    belly: "#e0f0ff",
    outline: "#4682b4",
    accent: "#ffd700",
    trail: "#ffffff",
    trailKind: "star",
    accessory: "goggles",
    turnFx: "ring",
    turnSnd: "woosh",
    turnColor: "#ffffff",
    unlockAt: 1500,
    family: "bird",
  },
  {
    id: "infinity",
    name: "Infinity",
    price: 0,
    blurb: "Climbed until the numbers stopped making sense. Stair 3000.",
    body: "#1a0033",
    belly: "#4b0082",
    outline: "#0a001a",
    accent: "#00ffff",
    trail: "#00ffff",
    trailKind: "star",
    accessory: "halo",
    freckles: true,
    turnFx: "stardust",
    turnSnd: "chime",
    turnColor: "#00ffff",
    unlockAt: 3000,
    family: "ghost",
  },
  {
    id: "jolly",
    name: "Jolly",
    price: 1100,
    blurb: "Ho ho ho. Climbs with a sack full of momentum.",
    body: "#c41e3a",
    belly: "#ffffff",
    outline: "#8b0000",
    accent: "#228b22",
    trail: "#ffffff",
    trailKind: "puff",
    accessory: "beanie",
    turnFx: "snow",
    turnSnd: "chime",
    turnColor: "#ffffff",
    family: "knight",
  },
  {
    id: "spooky",
    name: "Spooky",
    price: 1100,
    blurb: "Carves his name into every stair. Boo.",
    body: "#ff7518",
    belly: "#ffd699",
    outline: "#8b4500",
    accent: "#000000",
    trail: "#ffb347",
    trailKind: "flame",
    accessory: "tophat",
    turnFx: "poof",
    turnSnd: "thud",
    turnColor: "#ff7518",
    family: "ghost",
  },
  {
    id: "lucky",
    name: "Lucky",
    price: 1100,
    blurb: "Four-leaf clover in one hand, stair rail in the other.",
    body: "#32cd32",
    belly: "#c0ffc0",
    outline: "#006400",
    accent: "#ffd700",
    trail: "#90ee90",
    trailKind: "spark",
    accessory: "tophat",
    turnFx: "sparkle",
    turnSnd: "bling",
    turnColor: "#ffd700",
    family: "cat",
  },
  {
    id: "mochi",
    name: "Mochi",
    price: 400,
    blurb: "Soft, squishy, and surprisingly determined.",
    body: "#ffc0cb",
    belly: "#fff0f5",
    outline: "#db7093",
    accent: "#ff69b4",
    trail: "#ffd0e0",
    trailKind: "puff",
    accessory: "ribbon",
    turnFx: "heart",
    turnSnd: "pop",
    turnColor: "#ffd0e0",
    family: "cat",
  },
  {
    id: "toast",
    name: "Toast",
    price: 300,
    blurb: "Perfectly browned. Always lands butter-side up.",
    body: "#deb887",
    belly: "#f5deb3",
    outline: "#8b7355",
    accent: "#ffd700",
    trail: "#f5deb3",
    trailKind: "puff",
    accessory: "none",
    turnFx: "poof",
    turnSnd: "pop",
    turnColor: "#f5deb3",
    family: "blob",
  },
  {
    id: "noodle",
    name: "Noodle",
    price: 450,
    blurb: "Long, wiggly, and impossible to pin down.",
    body: "#f4d03f",
    belly: "#fef9e7",
    outline: "#b7950b",
    accent: "#e67e22",
    trail: "#fef9e7",
    trailKind: "puff",
    accessory: "bandana",
    turnFx: "ring",
    turnSnd: "boing",
    turnColor: "#fef9e7",
    family: "long",
  },
  {
    id: "pebble",
    name: "Pebble",
    price: 350,
    blurb: "Small, round, and absolutely not to be underestimated.",
    body: "#808080",
    belly: "#c0c0c0",
    outline: "#404040",
    accent: "#a9a9a9",
    trail: "#d3d3d3",
    trailKind: "puff",
    accessory: "none",
    turnFx: "ring",
    turnSnd: "thud",
    turnColor: "#d3d3d3",
    family: "blob",
  },
  {
    id: "raven",
    name: "Raven",
    price: 700,
    blurb: "Nevermore will a stair go unclimbed.",
    body: "#2f2f2f",
    belly: "#4a4a4a",
    outline: "#0a0a0a",
    accent: "#8b0000",
    trail: "#4a4a4a",
    trailKind: "spark",
    accessory: "bandana",
    turnFx: "poof",
    turnSnd: "woosh",
    turnColor: "#8b0000",
    family: "bird",
  },
  {
    id: "viper",
    name: "Viper",
    price: 850,
    blurb: "Strikes fast, climbs faster. Venom optional.",
    body: "#228b22",
    belly: "#90ee90",
    outline: "#006400",
    accent: "#ffff00",
    trail: "#90ee90",
    trailKind: "spark",
    accessory: "bandana",
    turnFx: "zap",
    turnSnd: "zap",
    turnColor: "#ffff00",
    family: "long",
  },
  {
    id: "phantom",
    name: "Phantom",
    price: 1600,
    blurb: "Half here, half there. Fully committed to the climb.",
    body: "#e6e6fa",
    belly: "#ffffff",
    outline: "#b0b0d0",
    accent: "#8a2be2",
    trail: "#d8bfd8",
    trailKind: "star",
    accessory: "none",
    freckles: true,
    turnFx: "stardust",
    turnSnd: "woosh",
    turnColor: "#d8bfd8",
    family: "ghost",
  },
  {
    id: "disco",
    name: "Disco",
    price: 1700,
    blurb: "Every stair becomes a dance floor. Stayin' alive.",
    body: "#ff00ff",
    belly: "#ffb6ff",
    outline: "#8b008b",
    accent: "#ffff00",
    trail: "#ffb6ff",
    trailKind: "spark",
    accessory: "party",
    turnFx: "confetti",
    turnSnd: "bling",
    turnColor: "#ffff00",
    family: "fancy",
  },
  {
    id: "pirate",
    name: "Pirate",
    price: 1400,
    blurb: "Arr! The stairs be me treasure map.",
    body: "#8b4513",
    belly: "#d2b48c",
    outline: "#4a2c0a",
    accent: "#ff0000",
    trail: "#d2b48c",
    trailKind: "puff",
    accessory: "bandana",
    turnFx: "ring",
    turnSnd: "woosh",
    turnColor: "#ff0000",
    family: "knight",
  },
  {
    id: "ninja",
    name: "Ninja",
    price: 1400,
    blurb: "You didn't see them climb. They were never here.",
    body: "#1a1a1a",
    belly: "#2d2d2d",
    outline: "#000000",
    accent: "#ff0000",
    trail: "#2d2d2d",
    trailKind: "spark",
    accessory: "headband",
    turnFx: "poof",
    turnSnd: "woosh",
    turnColor: "#ff0000",
    family: "knight",
  },
  {
    id: "comet",
    name: "Comet",
    price: 1900,
    blurb: "Leaves a trail of ice and dust. Orbit not required.",
    body: "#b0e0e6",
    belly: "#e0f8ff",
    outline: "#4682b4",
    accent: "#ffd700",
    trail: "#e0f8ff",
    trailKind: "star",
    accessory: "none",
    turnFx: "stardust",
    turnSnd: "twinkle",
    turnColor: "#e0f8ff",
    family: "bird",
  },
  {
    id: "quasar",
    name: "Quasar",
    price: 2600,
    blurb: "Brighter than a galaxy. Louder than a supernova.",
    body: "#ffffff",
    belly: "#ffffe0",
    outline: "#ffa500",
    accent: "#ff4500",
    trail: "#ffffe0",
    trailKind: "star",
    accessory: "goggles",
    turnFx: "stardust",
    turnSnd: "twinkle",
    turnColor: "#ffffe0",
    family: "fancy",
  },
  {
    id: "eclipse",
    name: "Eclipse",
    price: 3200,
    blurb: "Blocks out the sun. Climbs in the shadows.",
    body: "#1a1a1a",
    belly: "#ff8c00",
    outline: "#000000",
    accent: "#ff8c00",
    trail: "#ff8c00",
    trailKind: "flame",
    accessory: "crown",
    turnFx: "ring",
    turnSnd: "woosh",
    turnColor: "#ff8c00",
    family: "ghost",
  },

  /* ================================================================
     SPECIAL GUEST — Loggo
     ================================================================ */
  {
    id: "loggo",
    name: "Loggo",
    price: 0,
    blurb: "A wooden log that picked up a bat. Tongue twister approved.",
    body: "#c58a4a",
    belly: "#a06a30",
    outline: "#5c3a17",
    accent: "#8a5a24",
    trail: "#e6c290",
    trailKind: "puff",
    accessory: "bat",
    turnFx: "poof",
    turnSnd: "thud",
    turnColor: "#c58a4a",
    unlockAt: 1337,
    family: "wooden",
  },
];

export const skinById = (id: string): SkinDef =>
  SKINS.find((s) => s.id === id) ?? SKINS[0];